pub use crate::domain::implement::commands::v2::{
    add_file_v2, analyze_import_file, analyze_pmp_import, close_active_project,
    copy_text_to_system_clipboard, create_pmp_v2, delete_project, fetch_url_as_data_url,
    force_save_project, get_active_project, get_app_config, get_dashboard_extension_dist,
    get_dashboard_project_stats, get_dashboard_top_files, get_pending_pmp_path,
    get_project_bootstrap_v2, get_project_tree, get_projects, get_recent_projects, get_stats_v2,
    index_project_files, load_pmp_file, open_project_bootstrap, post_collaboration_json,
    read_binary_file, remove_recent_project, save_binary_file, save_binary_file_raw,
    save_last_opened_project, save_project, save_project_bom_table, save_recent_projects,
    search_v2, start_import_task, update_app_config, update_metadata_v2, update_project_state_v2,
};

pub use crate::domain::implement::commands::v2::{
    __cmd__add_file_v2, __cmd__analyze_import_file, __cmd__analyze_pmp_import,
    __cmd__close_active_project, __cmd__copy_text_to_system_clipboard, __cmd__create_pmp_v2,
    __cmd__delete_project, __cmd__fetch_url_as_data_url, __cmd__force_save_project,
    __cmd__get_active_project, __cmd__get_app_config, __cmd__get_dashboard_extension_dist,
    __cmd__get_dashboard_project_stats, __cmd__get_dashboard_top_files,
    __cmd__get_pending_pmp_path, __cmd__get_project_bootstrap_v2, __cmd__get_project_tree,
    __cmd__get_projects, __cmd__get_recent_projects, __cmd__get_stats_v2,
    __cmd__index_project_files, __cmd__load_pmp_file, __cmd__open_project_bootstrap,
    __cmd__post_collaboration_json, __cmd__read_binary_file, __cmd__remove_recent_project,
    __cmd__save_binary_file, __cmd__save_binary_file_raw, __cmd__save_last_opened_project,
    __cmd__save_project, __cmd__save_project_bom_table, __cmd__save_recent_projects,
    __cmd__search_v2, __cmd__start_import_task, __cmd__update_app_config,
    __cmd__update_metadata_v2, __cmd__update_project_state_v2,
};

#[macro_export]
macro_rules! register_storage_commands {
    () => {
        $crate::domain::implement::commands::modules::storage_commands::create_pmp_v2,
        $crate::domain::implement::commands::modules::storage_commands::add_file_v2,
        $crate::domain::implement::commands::modules::storage_commands::update_metadata_v2,
        $crate::domain::implement::commands::modules::storage_commands::get_app_config,
        $crate::domain::implement::commands::modules::storage_commands::update_app_config,
        $crate::domain::implement::commands::modules::storage_commands::get_pending_pmp_path,
        $crate::domain::implement::commands::modules::storage_commands::get_recent_projects,
        $crate::domain::implement::commands::modules::storage_commands::analyze_import_file,
        $crate::domain::implement::commands::modules::storage_commands::analyze_pmp_import,
        $crate::domain::implement::commands::modules::storage_commands::save_binary_file,
        $crate::domain::implement::commands::modules::storage_commands::save_binary_file_raw,
        $crate::domain::implement::commands::modules::storage_commands::read_binary_file,
        $crate::domain::implement::commands::modules::storage_commands::copy_text_to_system_clipboard,
        $crate::domain::implement::commands::modules::storage_commands::fetch_url_as_data_url,
        $crate::domain::implement::commands::modules::storage_commands::post_collaboration_json,
        $crate::domain::implement::commands::modules::storage_commands::start_import_task,
        $crate::domain::implement::commands::modules::storage_commands::load_pmp_file,
        $crate::domain::implement::commands::modules::storage_commands::open_project_bootstrap,
        $crate::domain::implement::commands::modules::storage_commands::get_project_bootstrap_v2,
        $crate::domain::implement::commands::modules::storage_commands::get_active_project,
        $crate::domain::implement::commands::modules::storage_commands::get_project_tree,
        $crate::domain::implement::commands::modules::storage_commands::save_recent_projects,
        $crate::domain::implement::commands::modules::storage_commands::save_last_opened_project,
        $crate::domain::implement::commands::modules::storage_commands::index_project_files,
        $crate::domain::implement::commands::modules::storage_commands::search_v2,
        $crate::domain::implement::commands::modules::storage_commands::get_stats_v2,
        $crate::domain::implement::commands::modules::storage_commands::get_dashboard_project_stats,
        $crate::domain::implement::commands::modules::storage_commands::get_dashboard_extension_dist,
        $crate::domain::implement::commands::modules::storage_commands::get_dashboard_top_files,
        $crate::domain::implement::commands::modules::storage_commands::save_project,
        $crate::domain::implement::commands::modules::storage_commands::force_save_project,
        $crate::domain::implement::commands::modules::storage_commands::update_project_state_v2,
        $crate::domain::implement::commands::modules::storage_commands::save_project_bom_table,
        $crate::domain::implement::commands::modules::storage_commands::get_projects,
        $crate::domain::implement::commands::modules::storage_commands::close_active_project,
        $crate::domain::implement::commands::modules::storage_commands::remove_recent_project,
        $crate::domain::implement::commands::modules::storage_commands::delete_project
    };
}
