pub mod gis_commands;
pub mod modules;
pub mod v2;
pub mod v2_bridge;

#[macro_export]
macro_rules! register_tauri_commands {
    () => {
        tauri::generate_handler![
            // Storage & Project Commands
            $crate::domain::implement::commands::modules::storage_commands::create_pmp_v2,
            $crate::domain::implement::commands::modules::storage_commands::add_file_v2,
            $crate::domain::implement::commands::modules::storage_commands::update_metadata_v2,
            $crate::domain::implement::commands::modules::storage_commands::get_app_config,
            $crate::domain::implement::commands::modules::storage_commands::update_app_config,
            // AI Module Commands
            $crate::domain::implement::commands::modules::ai_commands::get_ai_config,
            $crate::domain::implement::commands::modules::ai_commands::update_ai_config,
            $crate::domain::implement::commands::modules::ai_commands::set_ai_api_key,
            $crate::domain::implement::commands::modules::ai_commands::delete_ai_api_key,
            $crate::domain::implement::commands::modules::ai_commands::get_ai_status,
            $crate::domain::implement::commands::modules::ai_commands::install_ai_models,
            $crate::domain::implement::commands::modules::ai_commands::cancel_ai_model_install,
            $crate::domain::implement::commands::modules::ai_commands::remove_ai_models,
            $crate::domain::implement::commands::modules::ai_commands::release_ai_memory,
            $crate::domain::implement::commands::modules::ai_commands::predict_task,
            $crate::domain::implement::commands::modules::ai_commands::analyze_contract_metadata,
            $crate::domain::implement::commands::modules::ai_commands::save_ai_correction,
            $crate::domain::implement::commands::modules::ai_commands::create_ai_conversation,
            $crate::domain::implement::commands::modules::ai_commands::list_ai_conversations,
            $crate::domain::implement::commands::modules::ai_commands::send_ai_message,
            $crate::domain::implement::commands::modules::ai_commands::cancel_ai_request,
            $crate::domain::implement::commands::modules::ai_commands::confirm_ai_action,
            $crate::domain::implement::commands::modules::ai_commands::reject_ai_action,
            // System & IO Commands
            $crate::domain::implement::commands::modules::storage_commands::get_pending_pmp_path,
            $crate::domain::implement::commands::modules::storage_commands::get_recent_projects,
            $crate::domain::implement::commands::modules::storage_commands::analyze_import_file,
            $crate::domain::implement::commands::modules::storage_commands::analyze_pmp_import,
            $crate::domain::implement::commands::modules::storage_commands::save_binary_file,
            $crate::domain::implement::commands::modules::storage_commands::save_binary_file_raw,
            $crate::domain::implement::commands::modules::storage_commands::read_binary_file,
            $crate::domain::implement::commands::modules::storage_commands::copy_text_to_system_clipboard,
            $crate::domain::implement::commands::modules::storage_commands::fetch_url_as_data_url,
            $crate::domain::implement::commands::modules::storage_commands::post_collaboration_json,
            $crate::domain::implement::commands::modules::storage_commands::start_import_task,
            // Sync Commands
            $crate::domain::implement::commands::modules::sync_commands::sync_v2_get_status,
            $crate::domain::implement::commands::modules::sync_commands::sync_v2_is_online,
            $crate::domain::implement::commands::modules::sync_commands::sync_v2_go_online,
            $crate::domain::implement::commands::modules::sync_commands::sync_v2_go_offline,
            $crate::domain::implement::commands::modules::sync_commands::sync_v2_start,
            $crate::domain::implement::commands::modules::sync_commands::get_pending_sync_outbox,
            $crate::domain::implement::commands::modules::sync_commands::mark_outbox_synced,
            // Project State & Indexing Commands
            $crate::domain::implement::commands::modules::project_commands::load_pmp_file,
            $crate::domain::implement::commands::modules::project_commands::open_project_bootstrap,
            $crate::domain::implement::commands::modules::project_commands::get_project_bootstrap_v2,
            $crate::domain::implement::commands::modules::project_commands::get_active_project,
            $crate::domain::implement::commands::modules::project_commands::get_project_tree,
            $crate::domain::implement::commands::modules::project_commands::save_recent_projects,
            $crate::domain::implement::commands::modules::project_commands::save_last_opened_project,
            $crate::domain::implement::commands::modules::storage_commands::index_project_files,
            $crate::domain::implement::commands::modules::storage_commands::search_v2,
            $crate::domain::implement::commands::modules::storage_commands::get_stats_v2,
            $crate::domain::implement::commands::modules::storage_commands::get_dashboard_project_stats,
            $crate::domain::implement::commands::modules::storage_commands::get_dashboard_extension_dist,
            $crate::domain::implement::commands::modules::storage_commands::get_dashboard_top_files,
            $crate::domain::implement::commands::modules::project_commands::invoke_design_event_batch,
            $crate::domain::implement::commands::modules::project_commands::normalize_metadata,
            $crate::domain::implement::commands::modules::project_commands::find_nearest_snap_point,
            $crate::domain::implement::commands::modules::project_commands::save_project,
            $crate::domain::implement::commands::modules::project_commands::force_save_project,
            $crate::domain::implement::commands::modules::project_commands::update_project_state_v2,
            $crate::domain::implement::commands::modules::project_commands::save_project_bom_table,
            // V2 Bridge & Fiber Commands
            $crate::domain::implement::commands::v2_bridge::query_projection_v2,
            $crate::domain::implement::commands::v2_bridge::get_fiber_inventory,
            $crate::domain::implement::commands::v2_bridge::get_fiber_cable_points,
            $crate::domain::implement::commands::v2_bridge::get_fiber_capacity,
            $crate::domain::implement::commands::v2_bridge::trace_fiber_circuit,
            $crate::domain::implement::commands::v2_bridge::validate_fiber_network,
            $crate::domain::implement::commands::v2_bridge::load_design_state_v2,
            $crate::domain::implement::commands::v2_bridge::query_visible_features_v2,
            $crate::domain::implement::commands::v2_bridge::get_map_tile_v2,
            $crate::domain::implement::commands::v2_bridge::build_map_tiles_v2,
            $crate::domain::implement::commands::v2_bridge::invalidate_map_tiles_v2,
            $crate::domain::implement::commands::v2_bridge::get_feature_detail_v2,
            $crate::domain::implement::commands::v2_bridge::get_task_dependencies_v2,
            $crate::domain::implement::commands::v2_bridge::get_content_types_v2,
            $crate::domain::implement::commands::v2_bridge::get_project_bom_table_v2,
            $crate::domain::implement::commands::v2_bridge::get_tasks,
            $crate::domain::implement::commands::v2_bridge::get_notes,
            $crate::domain::implement::commands::v2_bridge::get_contracts,
            $crate::domain::implement::commands::v2_bridge::get_materials,
            $crate::domain::implement::commands::v2_bridge::navigate_webview,
            $crate::domain::implement::commands::v2_bridge::eval_webview,
            $crate::domain::implement::commands::v2_bridge::get_webview_url,
            $crate::domain::implement::commands::v2_bridge::capture_webview_png,
            $crate::domain::implement::commands::v2_bridge::get_task_dependencies,
            $crate::domain::implement::commands::v2_bridge::get_content_types,
            $crate::domain::implement::commands::v2_bridge::get_project_bom_table,
            $crate::domain::implement::commands::v2_bridge::get_tasks_legacy,
            $crate::domain::implement::commands::v2_bridge::get_notes_legacy,
            $crate::domain::implement::commands::modules::project_commands::get_projects,
            $crate::domain::implement::commands::modules::project_commands::close_active_project,
            // Media Asset Commands
            $crate::domain::implement::commands::modules::media_commands::import_media_asset,
            $crate::domain::implement::commands::modules::media_commands::import_pmp_into_project,
            $crate::domain::implement::commands::modules::media_commands::delete_media_asset,
            $crate::domain::implement::commands::modules::media_commands::replace_media_asset,
            $crate::domain::implement::commands::modules::media_commands::resolve_media_asset,
            $crate::domain::implement::commands::modules::media_commands::get_report_section_site_photos,
            $crate::domain::implement::commands::modules::media_commands::optimize_project_storage,
            $crate::domain::implement::commands::modules::media_commands::get_project_storage_health,
            $crate::domain::implement::commands::modules::media_commands::analyze_project_media_recovery,
            $crate::domain::implement::commands::modules::media_commands::apply_project_media_recovery,
            $crate::domain::implement::commands::modules::project_commands::remove_recent_project,
            $crate::domain::implement::commands::modules::project_commands::delete_project,
            $crate::domain::implement::commands::modules::project_commands::undo_design_event,
            $crate::domain::implement::commands::modules::project_commands::redo_design_event,
            // Auth & License Commands
            $crate::domain::implement::auth::local_auth::get_current_user,
            $crate::domain::implement::auth::local_auth::local_login,
            $crate::domain::implement::auth::local_auth::local_register,
            $crate::domain::implement::auth::local_auth::logout_user,
            $crate::domain::implement::auth::local_auth::delete_local_account,
            $crate::domain::implement::auth::license::check_license,
            $crate::domain::implement::auth::license::activate_license,
            // GIS Commands
            $crate::domain::implement::commands::modules::gis_commands::st_geom_from_ewkt,
            $crate::domain::implement::commands::modules::gis_commands::st_as_ewkt,
            $crate::domain::implement::commands::modules::gis_commands::st_is_valid,
            $crate::domain::implement::commands::modules::gis_commands::st_make_valid,
            $crate::domain::implement::commands::modules::gis_commands::st_transform,
            $crate::domain::implement::commands::modules::gis_commands::st_measure_feature,
            $crate::domain::implement::commands::modules::gis_commands::st_spatial_relate,
            // Basemap Commands
            $crate::domain::implement::commands::modules::basemap_commands::get_basemap_tile,
            $crate::domain::implement::commands::modules::basemap_commands::prefetch_basemap_tiles,
            $crate::domain::implement::commands::modules::basemap_commands::get_basemap_cache_stats,
            $crate::domain::implement::commands::modules::basemap_commands::clear_basemap_tile_cache,
        ]
    };
}
